spring:
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 300000
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/mydb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    jwt:
      secret: ${JWT_SECRET}
    encryption:
      key: ${ENCRYPTION_KEY}
      vector: ${INIT_VECTOR}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      hikari:
        maximum-pool-size: 4
        minimum-idle: 2
        idle-timeout: 30000
        max-lifetime: 300000

api-keys:
  google: ${GOOGLE_API_KEY}
  openai: ${OPENAI_API_KEY}
  virustotal: ${VIRUSTOTAL_API_KEY}
  data:
    redis:
      host: localhost
      port: 6379