spring:
  # .env import
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  security:
    jwt:
      expiration-ms: 600000  # 10분
  mail:
    imap:
      host: imap.naver.com
      port: 993
      protocol: imaps
thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"
mail-settings:
  imap-hosts:
    naver.com: imap.naver.com
    gmail.com: imap.gmail.com
    dorazi02sev.shop: mail.dorazi02sev.shop
    outlook.com: outlook.office365.com
    office365.com: outlook.office365.com
api-limiting:
  daily-limit: 20